In [5]:
import numpy as np

# One dimensional arrays

In [6]:
one_dim_arr = np.array([10, 12])
print(one_dim_arr)

[10 12]


In [8]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [12]:
b = np.linspace(0, 100, 10)
print(b)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [14]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML!']
<U23


In [16]:
c = np.ones(3)
print(c)

[1. 1. 1.]


In [21]:
d = np.random.rand(3)
print(d)

[0.75333539 0.1980383  0.50873787]


# 2D Arrays

In [24]:
two_dim_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
e = np.array([1, 2, 3, 4, 5, 6])
f = np.reshape(
    e,
    (2, 3)
)
print(f)

[[1 2 3]
 [4 5 6]]
