# Matrix Multiplication

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, -1],
    [3, 0, -2]
], dtype=np.dtype(int))

print(A)

B = np.array([
    [4, 1],
    [-1, 0],
    [3, -3]
])

print(B)

[[ 1  2 -1]
 [ 3  0 -2]]
[[ 4  1]
 [-1  0]
 [ 3 -3]]


In [5]:
C = np.matmul(A, B)
print(C)

[[-1  4]
 [ 6  9]]


In [7]:
D = np.dot(B, A)
print(D)

[[ 7  8 -6]
 [-1 -2  1]
 [-6  6  3]]
